output "primary" {
  value = {
    region               = var.primary_region
    vpc_id               = module.vpc_primary.vpc_id
    eks_cluster_name      = module.eks_primary.cluster_name
    eks_cluster_endpoint  = module.eks_primary.cluster_endpoint
    documents_bucket_name = aws_s3_bucket.documents_primary.bucket
    rds_endpoint          = module.rds_primary.db_instance_endpoint
    redis_endpoint        = aws_elasticache_replication_group.redis_primary.primary_endpoint_address
  }
}

output "secondary" {
  value = var.enable_secondary_region ? {
    region               = var.secondary_region
    vpc_id               = module.vpc_secondary[0].vpc_id
    eks_cluster_name      = module.eks_secondary[0].cluster_name
    eks_cluster_endpoint  = module.eks_secondary[0].cluster_endpoint
    documents_bucket_name = aws_s3_bucket.documents_secondary[0].bucket
    rds_endpoint          = module.rds_secondary[0].db_instance_endpoint
    redis_endpoint        = aws_elasticache_replication_group.redis_secondary[0].primary_endpoint_address
  } : null
}

output "rds_master_user_secret_arns" {
  description = "Secrets Manager secret ARNs that store RDS master passwords (generated by AWS)."
  value = {
    primary   = module.rds_primary.db_instance_master_user_secret_arn
    secondary = var.enable_secondary_region ? module.rds_secondary[0].db_instance_master_user_secret_arn : null
  }
  sensitive = true
}
